### ISSUE TITLE
How to make tldextract do not down load public_suffix_list.dat

### ISSUE THREAD

**Issue by SQYYHCJ** [john-kurkowski/tldextract#332]
I want to use the DrissionPage deponds on tldextract in  offline env.
I use pyinstaller packaged my project. The exception throwed when I run the App.

_Exception reading Public Suffix List url https://publicsuffix.org/list/public_suffix_list.dat
Traceback (most recent call last):
  File "tldextract\cache.py", line 209, in run_and_cache
  File "tldextract\cache.py", line 111, in get
KeyError: "namespace: publicsuffix.org-tlds key: {'urls': ('https://publicsuffix.org/list/public_suffix_list.dat', 'https://raw.githubusercontent.com/publicsuffix/list/master/public_suffix_list.dat'), 'fallback_to_snapshot': True}"_

**Comment by ajasonwang** [comment]
I have the same issue, also trying setting suffix_list_urls=None in main() but no luck, will there be a global option to disable default live http request?

**Comment by john-kurkowski** [comment]
Could you share repro steps? The full code you're using and the full error message?

When I clear my cache

```py
>>> import tldextract

>>> tldextract.tldextract.update()
```

disconnect from the Internet, then run [these 2 lines from the README about no live HTTP fetching](https://github.com/john-kurkowski/tldextract/blob/5.1.2/README.md#note-about-caching),

```py
>>> no_fetch_extract = tldextract.TLDExtract(suffix_list_urls=())
>>> no_fetch_extract('http://www.google.com')
ExtractResult(subdomain='www', domain='google', suffix='com', is_private=False)
```

it works for me, no raised exception.

**Comment by john-kurkowski** [comment]
Closing due to inactivity. Let me know if you have more details about your issue.
